networks:
  bench: {}
services:
  client:
    image: new_name
    container_name: new_name
    depends_on:
    - server
    environment:
      BENCHMARK_SYSTEM_URL: server
    links:
    - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: benchmark-server-logging
    restart: always
    volumes:
    - /Users/oleh/Lab/HOBBIT/docker_api_python/container_manager/dataset:/dataset
    - ../logs:/logs
version: '3'
