networks:
  bench: {}
services:
  client:
    container_name: client-app-docker_api_python_client
    depends_on:
    - server
    environment:
      BENCHMARK_SYSTEM_URL: server
    image: olehbodunov/docker_api_python_client
    links:
    - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: benchmark-server-logging
    restart: always
    volumes:
    - /Users/oleh/Lab/HOBBIT/docker_api_python/container_manager/dataset:/dataset
    - ../logs/docker_api_python_client:/logs
version: '3'
